modLoader = "javafml"
loaderVersion = "[41,)"
issueTrackerURL = "https://github.com/Wulian233/Chat-Impressive-Animation/issues"
license = "MIT"

[[mods]]
modId = "chatimpressiveanimation"
version = "${version}"
displayName = "Chat Impressive Animation"
displayURL = "https://github.com/Wulian233/Chat-Impressive-Animation/"
authors = "Wulian233, TexTrue"
description = '''
This mod makes the chat look better by adding animations. Such as opening chat, sending messages. It also removes the message indicator.
'''
logoFile = "icon.png"

[[dependencies.chatimpressiveanimation]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.chatimpressiveanimation]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20,1.20.5)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.chatimpressiveanimation]]
    modId = "architectury"
    mandatory = true
    versionRange = "*"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.chatimpressiveanimation]]
		modId = "cloth_config"
		mandatory = true
		versionRange = "*"
		ordering = "AFTER"
		side = "BOTH"
