modLoader = "javafml"
loaderVersion = "[41,)"
issueTrackerURL = "https://github.com/Wulian233/Chat-Impressive-Animation/issues"
license = "MIT"

[[mods]]
modId = "chatimpressiveanimation"
version = "${version}"
displayName = "Chat Impressive Animation"
displayURL = "https://github.com/Wulian233/Chat-Impressive-Animation/"
authors = "Wulian233, TexTrue"
description = '''
Makes chat messages appear with a smooth animation.
'''
logoFile = "icon.png"

[[dependencies.chatimpressiveanimation]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.chatimpressiveanimation]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.chatimpressiveanimation]]
    modId = "architectury"
    mandatory = true
    versionRange = "*"
    ordering = "AFTER"
    side = "BOTH"
