org.gradle.jvmargs=-Xmx2048M

minecraft_version=1.20.4
enabled_platforms=fabric,forge,neoforge
yarn_mappings=1.20.4+build.3

archives_base_name=ChatImpressiveAnimation
mod_version=1.5.0
maven_group=com.wulian.chatimpressiveanimation

clothconfig_version=13.0.138
modmenu_version=9.2.0

fabric_loader_version=0.18.4
fabric_api_version=0.97.3+1.20.4

forge_version=1.20.4-49.2.4

neoforge_version=20.4.251
