org.gradle.jvmargs=-Xmx2048M

minecraft_version=26.1.2
enabled_platforms=fabric,neoforge

archives_base_name=ChatImpressiveAnimation
mod_version=1.6.0
maven_group=com.wulian.chatimpressiveanimation

clothconfig_version=26.1.154
modmenu_version=18.0.0-alpha.8
fabric_loader_version=0.19.2
fabric_api_version=0.146.1+26.1.2

neoforge_version=26.1.2.15-beta
